### ISSUE TITLE
Can't seem to run this code

### ISSUE THREAD

**Issue by lisacodes88** [Neurotech-HQ/pysimilar#1]
Traceback (most recent call last):
  File "C:\Users\lsa\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Python 3.10\cosinefin.py", line 4, in <module>
    comparison_result = pysimilar.compare_documents('C:/Users/lsa/desktop/sap')
  File "C:\Users\lsa\AppData\Local\Programs\Python\Python310\lib\site-packages\pysimilar\__init__.py", line 117, in compare_documents
    loaded_documents: Dict = self.load_files(path_to_documents)
  File "C:\Users\lsa\AppData\Local\Programs\Python\Python310\lib\site-packages\pysimilar\__init__.py", line 71, in load_files
    load_documents: List[str] = [self.load_file(path_to_document)
  File "C:\Users\lsa\AppData\Local\Programs\Python\Python310\lib\site-packages\pysimilar\__init__.py", line 71, in <listcomp>
    load_documents: List[str] = [self.load_file(path_to_document)
  File "C:\Users\lsa\AppData\Local\Programs\Python\Python310\lib\site-packages\pysimilar\__init__.py", line 66, in load_file
    content = document.read()
  File "C:\Users\lsa\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 241: character maps to <undefined>

**Comment by Kalebu** [comment]
<samp>
Hi @lisacodes88 

It looks like there is an issue with encoding while loading the files

I have updated it to use *latin-1* encoding instead of the default *utf-8*

Please update your package and let me know if it works 

```bash
pip install --upgrade pysimilar
```

Thank you 
Kalebu
</samp>

**Comment by Kalebu** [comment]
Hi @lisacodes88, I hope you were able to fix it, I will now close this issue
